// src/sections/Hero.jsx
import BlueDots from "../assets/images/blue-dots.svg?react";

export default function Hero() {
    return (
        // <section className="relative mx-auto mb-60 flex h-screen max-w-[1200px] flex-col justify-center px-7 sm:mt-10 sm:px-13 md:mt-10 md:mb-70 md:px-26 lg:px-39">
        //     <div>
        //         <p className="font-reddit text-accent-clr text-hero-intro mb-8 text-base md:mb-7">
        //             Hi, my name is
        //         </p>
        //         <h1 className="text-h1-sizing text-header-txt-clr header-leading leading-header font-bold tracking-wider">
        //             Trenton Avilla
        //             <span className="text-accent-clr">.</span>
        //         </h1>
        //         <h2 className="text-h2-sizing text-main-txt-clr leading-header-h2 mt-2 font-semibold tracking-wide">
        //             I am a Front-End Developer
        //             <span className="text-accent-clr">.</span>
        //         </h2>
        //         <p className="text-main-txt-clr text-hero-desc mt-6 max-w-lg sm:mt-6">
        //             I like to design and build things for the web
        //             <span className="text-accent-clr">.</span> I currently enjoy
        //             using React and Tailwind to create functional and engaging
        //             websites<span className="text-accent-clr">.</span>
        //         </p>
        //         <a
        //             href="#projects"
        //             className="text-accent-clr hover:bg-accent-clr hover:text-main-bg-clr mt-14 inline-block cursor-pointer rounded-sm border px-6 py-4 duration-300 hover:transition-colors"
        //             onClick={(e) => handleSmoothScroll(e, "projects")}
        //             aria-label="Scroll to Projects section"
        //         >
        //             Recent Work
        //         </a>
        //     </div>
        // </section>

        <section className="relative">
            <div className="mx-auto mb-60 flex h-screen max-w-[1200px] flex-col justify-center px-7 sm:mt-10 sm:px-13 md:mt-10 md:px-26 lg:px-39">
                <p className="font-reddit text-accent-clr text-hero-intro mb-8 text-base md:mb-7">
                    Hi, my name is
                </p>
                <h1 className="text-h1-sizing text-header-txt-clr header-leading leading-header font-bold tracking-wider">
                    Trenton Avilla
                    <span className="text-accent-clr">.</span>
                </h1>
                <h2 className="text-h2-sizing text-main-txt-clr leading-header-h2 mt-2 font-semibold tracking-wide">
                    I am a Front-End Developer
                    <span className="text-accent-clr">.</span>
                </h2>
                <p className="text-main-txt-clr text-hero-desc mt-6 max-w-lg sm:mt-6">
                    I like to design and build things for the web
                    <span className="text-accent-clr">.</span> I currently enjoy
                    using React and Tailwind to create functional and engaging
                    websites<span className="text-accent-clr">.</span>
                </p>
                <a
                    href="#projects"
                    className="text-accent-clr hover:bg-accent-clr hover:text-main-bg-clr mt-14 inline-block w-fit cursor-pointer rounded-sm border px-6 py-4 duration-300 hover:transition-colors"
                    onClick={(e) => handleSmoothScroll(e, "projects")}
                    aria-label="Scroll to Projects section"
                >
                    Recent Work
                </a>
            </div>
            <BlueDots
                className="absolute -right-6 -bottom-[160px] -z-1 hidden rotate-180 md:block xl:hidden"
                width="400"
                height="400"
            />
        </section>
    );
}

// src/components/sections/Hero.svelte
<script>
</script>

<section>
    <div class="hero-container">
        <p>Hi, my name is</p>
        <h1>Trenton Avilla<span>.</span></h1>
        <h2>I am a Front-End Developer<span>.</span></h2>
        <p>
            I like to design and build things for the web. I currently enjoy
            using React and Tailwind to create functional and engaging websites<span
                >.</span
            >
        </p>
        <a href="#projects">Recent Work</a>
    </div>
    <!-- todo: Add blue dot images, same spot of different? -->
    <!-- <div> -->
    <!-- blue dots -->
    <!-- </div> -->
</section>

<style>
    section {
        display: flex;
        flex-direction: column;
        justify-content: center;
        height: 100vh;
        /* padding-inline: 1.75rem; */

        /* todo: Assigned padding-inline to <main>, keep at <main> or move to <section> elements? */
        /* @media (width >= 480px) {
            padding-inline: 3.25rem;
        }
        @media (width > 768px) {
            padding-inline: 6.5rem;
        }

        @media (width >= 1000px) {
            padding-inline: 9.75rem;
        } */

        span {
            color: var(--accent-clr);
        }
    }

    .hero-container {
        margin-block-start: 2.5rem;

        h1 {
            font-size: clamp(
                2.25rem,
                0.6346rem + 5.3846vw,
                4rem
            ); /* 480px - 1000px */
            font-weight: 700;
            line-height: clamp(
                2rem,
                0.1538rem + 6.1538vw,
                4rem
            ); /* 480px - 1000px */
            letter-spacing: 0.05em;
            color: var(--main-header-clr);
            margin-block-end: 0.5rem;
        }

        h2 {
            font-size: clamp(
                1.875rem,
                0.375rem + 5vw,
                3.5rem
            ); /* 480px - 1000px */
            font-weight: 600;
            line-height: clamp(
                2rem,
                0.6154rem + 4.6154vw,
                3.5rem
            ); /* 480px - 1000px */
            letter-spacing: 0.025em;
            color: var(--main-txt-clr);
            margin-block-end: 1.5rem;
        }

        p:first-of-type {
            font-family: 'Reddit-Mono';
            font-size: clamp(
                1rem,
                0.8956rem + 0.4773vw,
                1.125rem
            ); /* 350px - 769px */
            color: var(--accent-clr);
            margin-block-end: 2rem;

            @media (width > 768px) {
                margin-block-end: 1.75rem;
            }
        }

        p {
            font-size: clamp(
                1rem,
                0.7912rem + 0.9547vw,
                1.25rem
            ); /* 350px - 769px */
            color: var(--main-txt-clr);
            max-width: 32rem;
            margin-block-end: 3.5rem;
        }

        a {
            display: inline-block;
            color: var(--accent-clr);
            border: 1px solid var(--accent-clr);
            border-radius: 0.25rem;
            padding: 1rem 1.5rem;
            transition:
                color 0.3s ease,
                background-color 0.3s ease;

            &:hover {
                background-color: var(--accent-clr);
                color: var(--bg-clr);
            }
        }
    }
</style>
