// src/components/layout/Footer.svelte
<script>
    import Instagram from '../../assets/icons/Instagram.svelte';
    import Linkedin from '../../assets/icons/Linkedin.svelte';
    import Github from '../../assets/icons/Github.svelte';
</script>

<footer>
    <div class="link-container">
        <a
            href="https://www.instagram.com/trent_av/"
            target="_blank"
            aria-label="Instagram link"
        >
            <Instagram width="24" height="24" />
        </a>
        <a
            href="https://www.linkedin.com/in/trent-avilla/"
            target="_blank"
            aria-label="Linkedin link"
        >
            <Linkedin width="24" height="24" />
        </a>
        <a
            href="https://github.com/vhalen0515"
            target="_blank"
            aria-label="GitHub link"
        >
            <Github width="24" height="24" />
        </a>
    </div>
    <!-- <div> -->
    <p>
        Copyright © {new Date().getFullYear()} Trent Avilla. All Rights Reserved.
    </p>
    <!-- </div> -->
</footer>

<style>
    footer {
        padding-inline: 1.75rem;
        margin-block-start: 13rem;
    }

    .link-container {
        display: flex;
        justify-content: center;
        gap: 1.5rem;

        a {
            color: var(--main-txt-clr);
            padding: 0.5rem 0.75rem;
            transition:
                color 0.3s ease,
                transform 0.3s ease;

            &:hover {
                color: var(--accent-clr);
                transform: translateY(-3px);
            }
        }
    }

    p {
        font-family: 'Reddit-Mono';
        font-size: 0.75rem;
        color: var(--main-txt-clr);
        text-align: center;
        margin-block: 0.75rem;

        @media(width >= 480px) {
            margin-block: 1.5rem
        }
    }
</style>

// src/components/Footer.jsx
import InstagramIcon from "../assets/icons/instagram.svg?react";
import LinkedinIcon from "../assets/icons/linkedin.svg?react";
import GithubIcon from "../assets/icons/github.svg?react";

export default function Footer() {
    return (
        <footer className="mx-auto mt-40 flex max-w-[1200px] flex-col items-center px-7 sm:mt-36 md:mt-36 sm:px-13 md:px-26 lg:px-39">
            <div className="flex gap-6 md:hidden">
                <a
                    href="https://www.instagram.com/trent_av/"
                    target="_blank"
                    className="text-main-txt-clr hover:text-accent-clr px-3 py-2 transition-transform duration-300 hover:translate-y-[-3px]"
                    aria-label="Instagram link"
                >
                    <InstagramIcon width="24" height="24" />
                </a>
                <a
                    href="https://www.linkedin.com/in/trent-avilla/"
                    target="_blank"
                    className="text-main-txt-clr hover:text-accent-clr px-3 py-2 transition-transform duration-300 hover:translate-y-[-3px]"
                    aria-label="Linkedin link"
                >
                    <LinkedinIcon width="24" height="24" />
                </a>
                <a
                    href="https://github.com/vhalen0515"
                    target="_blank"
                    className="text-main-txt-clr hover:text-accent-clr px-3 py-2 transition-transform duration-300 hover:translate-y-[-3px]"
                    aria-label="GitHub link"
                >
                    <GithubIcon width="24" height="24" />
                </a>
            </div>
            <div className="text-main-txt-clr font-reddit my-3 flex flex-col gap-1 text-center text-xs sm:my-6 sm:gap-2">
                <p>Created with React and Tailwind.</p>
                <p>
                    Copyright © {new Date().getFullYear()} Trent Avilla. All
                    Rights Reserved.
                </p>
            </div>
        </footer>
    );
}
