// src/components/layout/Header.svelte
<script>
    // actions & transitions
    import { reveal } from '../actions/reveal.js';
    import { slide } from 'svelte/transition';

    // logo
    import Logo from '../../assets/logos/logo.svg';

    // lifecycle
    import { onMount, onDestroy } from 'svelte';

    /* -------------------------------------
       State
    ------------------------------------- */
    let isOpen = false;
    let showHeader = true;
    let lastScrollY = 0;
    let isScrollingUp = false;
    let isAtTop = true;
    // let mounted = false;

    /* -------------------------------------
       Menu behavior
    ------------------------------------- */
    function toggleMenu() {
        isOpen = !isOpen;
    }

    // Prevent body scroll when mobile menu is open
    $: if (isOpen) {
        document.body.classList.add('no-scroll');
    } else {
        document.body.classList.remove('no-scroll');
    }

    // $: if (mounted) {
    //     document.body.classList.toggle('no-scroll', isOpen);
    // }

    /* -------------------------------------
       Scroll behavior (desktop)
    ------------------------------------- */
    function handleScroll() {
        const currentScrollY = window.scrollY;

        isScrollingUp = currentScrollY < lastScrollY;
        isAtTop = currentScrollY < 50;

        showHeader = isScrollingUp || isAtTop;

        lastScrollY = currentScrollY;
    }

    /* -------------------------------------
       Lifecycle
    ------------------------------------- */
    onMount(() => {
        // mounted = true;
        window.addEventListener('scroll', handleScroll);
    });

    onDestroy(() => {
        window.removeEventListener('scroll', handleScroll);
        // document.body.classList.remove('no-scroll');
    });
</script>

<!-- mark: -->

<header class:hide={!showHeader} class:blur={!isAtTop && showHeader && !isOpen}>
    <div class="header-container">
        <a
            use:reveal={{ y: 0 }}
            href="https://www.trent-avilla.com/"
            aria-label="Go to homepage"
        >
            <img class="logo" src={Logo} alt="" />
        </a>

        <!-- mobile menu button -->
        <button
            use:reveal={{ y: 0 }}
            class="hamburger"
            class:is-open={isOpen}
            on:click={toggleMenu}
            aria-label="Menu"
            aria-expanded={isOpen}
        >
            <span></span>
            <span></span>
            <span></span>
        </button>

        <!-- desktop menu -->
        <nav class="desktop-nav">
            <ul>
                <li use:reveal={{ y: -24, duration: 0.4 }}>
                    <a href="#about">About</a>
                </li>
                <li use:reveal={{ y: -24, delay: 0.1, duration: 0.4 }}>
                    <a href="#experience">Experience</a>
                </li>
                <li use:reveal={{ y: -24, delay: 0.2, duration: 0.4 }}>
                    <a href="#projects">Projects</a>
                </li>
                <li use:reveal={{ y: -24, delay: 0.3, duration: 0.4 }}>
                    <a href="#contact">Contact</a>
                </li>
            </ul>
        </nav>
    </div>
</header>

<!-- mobile menu popout -->
{#if isOpen}
    <nav
        class="mobile-nav"
        class:is-open={isOpen}
        transition:slide={{ axis: 'y', duration: 300 }}
        aria-label="Mobile navigation"
    >
        <ul>
            <li>
                <a on:click={toggleMenu} href="#about">About</a>
            </li>
            <li>
                <a on:click={toggleMenu} href="#experience">Experience</a>
            </li>
            <li>
                <a on:click={toggleMenu} href="#projects">Projects</a>
            </li>
            <li>
                <a on:click={toggleMenu} href="#contact">Contact</a>
            </li>
        </ul>
    </nav>
{/if}

<!-- mark: -->

<style>
    header {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 50;
        transition: transform 0.3s ease;
    }

    header.hide {
        transform: translateY(-100%);
    }

    header.blur {
        background-color: color-mix(in oklab, var(--bg-clr) 60%, transparent);
        backdrop-filter: blur(4px);
        -webkit-backdrop-filter: blur(4px);
    }

    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        max-width: 1280px;
        padding: 1.5rem;
        margin-inline: auto;

        .logo {
            width: 52px;
        }

        @media (width > 768px) {
            padding: 2rem 2.5rem;
        }
    }

    .hamburger {
        position: relative;
        width: 40px;
        height: 40px;
        background: none;
        border: none;
        cursor: pointer;
        z-index: 100;

        @media (width > 768px) {
            display: none;
        }

        span {
            position: absolute;
            left: 0%;
            transform-origin: center;
            height: 2px;
            background: var(--accent-clr);
            transition:
                transform 0.3s ease,
                opacity 0.15s ease,
                width 0.3s ease;

            &:nth-child(1) {
                top: 11px;
                width: 24px;
            }

            &:nth-child(2) {
                top: 19px;
                width: 32px;
            }

            &:nth-child(3) {
                top: 27px;
                width: 24px;
            }
        }
    }

    .hamburger.is-open span {
        &:nth-child(1) {
            width: 28px;
            transform: translateX(-0%) translateY(8px) rotate(45deg);
        }

        &:nth-child(2) {
            opacity: 0;
        }

        &:nth-child(3) {
            width: 28px;
            transform: translateX(-0%) translateY(-8px) rotate(-45deg);
        }
    }

    .mobile-nav {
        position: fixed;
        inset: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100dvh;
        overflow-y: auto;
        background: rgba(0, 0, 0, 0.8);
        /* backdrop-filter: blur(8px);
        -webkit-backdrop-filter: blur(8px); */
        z-index: 40;

        @media (height <= 510px) {
            justify-content: flex-start;
            padding-block: 8rem;
        }

        ul {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 2.25rem;

            li {
                padding: 0.625rem 1.125rem;

                a {
                    font-family: 'Reddit-Mono';
                    font-size: 1.5rem;
                    color: var(--main-txt-clr);
                    transition: color 0.3s ease;

                    &:hover {
                        color: var(--accent-clr);
                    }

                    &::before {
                        color: var(--accent-clr);
                        margin-right: 0.375rem;
                    }

                    @media (width >= 480px) {
                        font-size: 1.875rem;
                        line-height: 1.35;
                    }
                }

                &:nth-child(1) a::before {
                    content: '01.';
                }
                &:nth-child(2) a::before {
                    content: '02.';
                }
                &:nth-child(3) a::before {
                    content: '03.';
                }
                &:nth-child(4) a::before {
                    content: '04.';
                }
            }
        }
    }

    .desktop-nav {
        display: none;

        @media (width > 768px) {
            display: block;
        }

        ul {
            display: flex;

            li {
                a {
                    font-family: 'Reddit-Mono';
                    font-size: 0.875rem;
                    color: var(--main-txt-clr);
                    padding: 0.625rem 1.125rem;
                    transition: color 0.3s ease;

                    &:hover {
                        color: var(--accent-clr);
                    }

                    &::before {
                        color: var(--accent-clr);
                        margin-right: 0.375rem;
                    }
                }

                &:nth-child(1) a::before {
                    content: '01.';
                }
                &:nth-child(2) a::before {
                    content: '02.';
                }
                &:nth-child(3) a::before {
                    content: '03.';
                }
                &:nth-child(4) a::before {
                    content: '04.';
                }
            }
        }
    }
</style>

// src/components/Header.jsx
import { useEffect, useState } from "react";
import logo from "../assets/images/logo.webp";
import MobileMenu from "./MobileMenu.jsx";

export default function Header({ handleSmoothScroll }) {
    const [hidden, setHidden] = useState(false);
    const [showBg, setShowBg] = useState(false);
    const [lastScrollY, setLastScrollY] = useState(0);
    const [isOpen, setIsOpen] = useState(false);

    const toggleMenu = () => setIsOpen((prev) => !prev);

    // Tracks scrolling and header visibility
    useEffect(() => {
        const handleScroll = () => {
            const currentScrollY = window.scrollY;
            const isScrollingDown = currentScrollY > lastScrollY;
            const isPastThreshold = currentScrollY > 50;

            setHidden(isScrollingDown && isPastThreshold);
            setShowBg(!isScrollingDown && isPastThreshold);

            setLastScrollY(currentScrollY);
        };

        window.addEventListener("scroll", handleScroll);
        return () => window.removeEventListener("scroll", handleScroll);
    }, [lastScrollY]);

    // Prevent scrolling when mobile menu is open
    useEffect(() => {
        if (isOpen) {
            document.body.classList.add("overflow-hidden");
        } else {
            document.body.classList.remove("overflow-hidden");
        }

        return () => {
            document.body.classList.remove("overflow-hidden");
        };
    }, [isOpen]);

    return (
        <header
            className={`fixed top-0 left-0 z-50 w-full transition-transform duration-500 ease-in-out ${hidden ? "-translate-y-full" : "translate-y-0"} ${showBg ? "bg-main-bg-clr/50 backdrop-blur-xs" : ""}`}
        >
            <div className="font-reddit mx-auto flex w-full max-w-[1200px] items-center justify-between px-6 py-6 md:px-10 md:py-8">
                <a
                    href="https://www.trent-avilla.com/"
                    aria-label="Go to homepage"
                >
                    <img
                        className="box-content h-10 w-10 hover:cursor-pointer"
                        src={logo}
                        alt="Picture of logo"
                        width="40"
                        height="40"
                    />
                </a>

                {/* Mobile Menu */}
                <button
                    onClick={toggleMenu}
                    className="relative z-100 h-10 w-10 cursor-pointer md:hidden"
                    aria-label="Open mobile menu"
                >
                    <div className="absolute inset-0 flex flex-col justify-center gap-1.5 transition-all duration-300">
                        <span
                            className={`bg-accent-clr h-0.5 w-6 transition-transform duration-300 ${
                                isOpen ? "w-7 translate-y-2 rotate-45" : ""
                            }`}
                        ></span>
                        <span
                            className={`bg-accent-clr h-0.5 w-8 transition-all duration-100 ${
                                isOpen ? "opacity-0" : ""
                            }`}
                        ></span>
                        <span
                            className={`bg-accent-clr h-0.5 w-6 transition-transform duration-300 ${
                                isOpen ? "w-7 -translate-y-2 -rotate-45" : ""
                            }`}
                        ></span>
                    </div>
                </button>

                <MobileMenu
                    className="md:hidden"
                    isOpen={isOpen}
                    closeMenu={() => setIsOpen(false)}
                    handleSmoothScroll={handleSmoothScroll}
                />

                {/* Desktop Menu */}
                <nav className="hidden md:block">
                    <ul className="flex items-center text-sm">
                        <li>
                            <a
                                href="#about"
                                className="text-main-txt-clr hover:text-accent-clr before:text-accent-clr px-4.5 py-2.5 duration-300 before:mr-1.5 before:content-['01.'] hover:cursor-pointer hover:transition-colors"
                                onClick={(e) => handleSmoothScroll(e, "about")}
                                aria-label="Scroll to About section"
                            >
                                About
                            </a>
                        </li>
                        <li>
                            <a
                                href="#experience"
                                className="text-main-txt-clr hover:text-accent-clr before:text-accent-clr px-4.5 py-2.5 duration-300 before:mr-1.5 before:content-['02.'] hover:cursor-pointer hover:transition-colors"
                                onClick={(e) =>
                                    handleSmoothScroll(e, "experience")
                                }
                                aria-label="Scroll to Experience section"
                            >
                                Experience
                            </a>
                        </li>
                        <li>
                            <a
                                href="#projects"
                                className="text-main-txt-clr hover:text-accent-clr before:text-accent-clr px-4.5 py-2.5 duration-300 before:mr-1.5 before:content-['03.'] hover:cursor-pointer hover:transition-colors"
                                onClick={(e) =>
                                    handleSmoothScroll(e, "projects")
                                }
                                aria-label="Scroll to Projects section"
                            >
                                Projects
                            </a>
                        </li>
                        <li>
                            <a
                                href="#contact"
                                className="text-main-txt-clr hover:text-accent-clr before:text-accent-clr px-4.5 py-2.5 duration-300 before:mr-1.5 before:content-['04.'] hover:cursor-pointer hover:transition-colors"
                                onClick={(e) =>
                                    handleSmoothScroll(e, "contact")
                                }
                                aria-label="Scroll to Contact section"
                            >
                                Contact
                            </a>
                        </li>
                        {/* <li className="ml-[1.125rem] hidden">
                            <a
                                href="#"
                                className="text-accent-clr hover:bg-accent-clr hover:border-accent-clr hover:text-main-bg-clr rounded-sm border px-4.5 py-2.5 duration-300 hover:transition-colors"
                                aria-label="Download Resume"
                            >
                                Resume
                            </a>
                        </li> */}
                    </ul>
                </nav>
            </div>
        </header>
    );
}
