// src/components/layout/RightSidebar.svelte
<script>
    // actions
    import { reveal } from '../actions/reveal.js';
</script>

<div use:reveal={{ y: 24, delay: 0.8, duration: 0.4 }} class="right-sidebar">
    <a
        href="mailto:tavilla04@gmail.com?subject=Web%20Development%20Project&body=I%20saw%20your%20portfolio%20and%20wanted%20to%20reach%20out!"
        aria-label="Send an email to Trent">tavilla04@gmail.com</a
    >
</div>

<style>
    .right-sidebar {
        position: fixed;
        bottom: 0;
        right: 1rem;
        display: none;
        flex-direction: column;
        align-items: center;

        @media (width > 768px) {
            display: flex;
        }

        @media (width >= 1000px) {
            right: 2.5rem;
        }

        @media (width >= 1360px) {
            right: calc((100vw - 1200px) / 2 - 40px);
        }

        &::after {
            content: '';
            background: var(--main-txt-clr);
            height: 5.75rem;
            width: 0.0625rem;
        }

        a {
            font-family: 'Reddit-Mono', monospace;
            font-size: 0.75rem;
            color: var(--main-txt-clr);
            letter-spacing: 1.5px;
            writing-mode: vertical-rl;
            padding-block: 0.5rem;
            margin-inline-end: 1.5rem;
            transition:
                color 0.3s ease,
                transform 0.3s ease;

            &:hover {
                color: var(--accent-clr);
                transform: translateY(-3px);
            }
        }
    }
</style>

// src/components/RightSidebar.jsx
export default function RightSidebar() {
    return (
        <div className="after:bg-main-txt-clr fixed right-4 lg:right-10 xl:right-[calc((100vw-1200px)/2-40px)] bottom-0 hidden items-center [writing-mode:vertical-rl] after:block after:h-23 after:w-0.25 after:content-[''] md:flex z-10">
            <a
                href="mailto:tavilla04@gmail.com?subject=Web%20Development%20Project&body=I%20saw%20your%20portfolio%20and%20wanted%20to%20reach%20out!"
                className="text-main-txt-clr hover:text-accent-clr font-reddit mx-6 py-2 text-xs tracking-[1.5px] transition-transform duration-300 hover:translate-y-[-3px]"
                aria-label="Send an email to Trent"
            >
                tavilla04@gmail.com
            </a>
        </div>
    );
}
