// src/components/sections/Projects.svelte
<script>
    // actions
    import { reveal } from '../actions/reveal.js';

    // component import
    import SliderPage from '../layout/SliderPage.svelte';
</script>

<section id="projects">
    <div class="projects-container">
        <h2 use:reveal>Some Recent Projects</h2>
        <div use:reveal>
            <SliderPage />
        </div>
    </div>
</section>

<style>
    .projects-container {
        h2 {
            display: flex;
            align-items: center;
            width: 100%;
            font-size: clamp(
                1.5rem,
                0.7941rem + 2.3529vw,
                1.75rem
            ); /* 480px - 650px */
            font-weight: 600;
            color: var(--main-header-clr);

            &::before {
                content: '03.';
                font-family: 'Reddit-Mono';
                font-size: clamp(
                    1rem,
                    0.2941rem + 2.3529vw,
                    1.25rem
                ); /* 480px - 650px */
                color: var(--accent-clr);
                margin-inline-end: 0.5rem;
            }

            &::after {
                content: '';
                flex: 1;
                height: 0.0625rem;
                background-color: var(--main-txt-clr);
                margin-inline-start: 1rem;

                @media (width >= 1000px) {
                    max-width: 21rem;
                }
            }
        }
    }
</style>

// src/sections/Projects.jsx
import SwiperComponent from "../components/SwiperComponent";
import { SLIDES } from "../data/slidesData.js";

export default function Projects() {
    return (
        <section id="projects" className="relative">
            <h2 className="text-header-txt-clr before:text-accent-clr before:font-reddit after:bg-main-txt-clr text-h2-section-sizing before:text-heading-num-sizing flex items-center font-semibold before:mr-2 before:font-normal before:content-['03.'] after:ml-4 after:h-0.25 after:flex-1 after:content-[''] md:after:w-1/4 md:after:flex-none lg:after:w-1/3">
                Some Recent Projects
            </h2>
            <SwiperComponent slides={SLIDES} />
        </section>
    );
}
