// src/App.svelte
<script>
    // Sections
    import Hero from './components/sections/Hero.svelte';
    import About from './components/sections/About.svelte';
    import Experience from './components/sections/Experience.svelte';
    import Projects from './components/sections/Projects.svelte';
    import Contact from './components/sections/Contact.svelte';

    // Components
    import Header from './components/layout/Header.svelte';
    import LeftSidebar from './components/layout/LeftSidebar.svelte';
    import RightSidebar from './components/layout/RightSidebar.svelte';
    import Footer from './components/layout/Footer.svelte';
</script>

<Header />
<LeftSidebar />
<RightSidebar />
<main>
    <Hero />
    <About />
    <Experience />
    <Projects />
    <Contact />
</main>
<Footer />

<style>
    main {
        display: flex;
        flex-direction: column;
        gap: 25rem;
        max-width: 1200px;
        margin-inline: auto;
        padding-inline: 1.75rem;

        @media (width >= 480px) {
            padding-inline: 3.25rem;
        }

        @media (width > 768px) {
            padding-inline: 6.5rem;
        }

        @media (width >= 1000px) {
            padding-inline: 9.75rem;
        }
    }
</style>

// src/App.jsx
// Sections
import Hero from "./sections/Hero";
import About from "./sections/About";
import Experience from "./sections/Experience";
import Projects from "./sections/Projects";
import Contact from "./sections/Contact";

// Components
import Header from "./components/Header";
import Footer from "./components/Footer";
import RightSidebar from "./components/RightSidebar.jsx";
import LeftSidebar from "./components/LeftSidebar.jsx";

export default function App() {
    return (
        // <>
        //     <Header />
        //     <main className="relative overflow-hidden">
        //         <div className="mx-auto max-w-[1200px] px-7 sm:px-13 md:px-26 lg:px-39">
        //             <Hero />
        //             <div className="space-y-60 md:space-y-70">
        //                 <About />
        //                 <Experience />
        //                 <Projects />
        //                 <Contact />
        //             </div>
        //             <RightSidebar />
        //             <LeftSidebar />
        //         </div>
        //         <BlueDots
        //             className="absolute top-120 -right-6 -z-1 hidden rotate-180 md:block xl:hidden"
        //             width="400"
        //             height="400"
        //         />
        //         {/* <BlueDots
        //             className="absolute top-390 -left-6 -z-1 hidden md:block xl:hidden"
        //             width="400"
        //             height="400"
        //         /> */}
        //         <BlueDots
        //             className="absolute top-540 -right-6 -z-1 hidden rotate-180 md:block xl:hidden"
        //             width="400"
        //             height="400"
        //         />
        //         <BlueDots
        //             className="absolute top-750 -left-6 -z-1 hidden md:block xl:hidden"
        //             width="400"
        //             height="400"
        //         />
        //     </main>
        //     <Footer />
        // </>

        <>
            <Header />
            <main className="overflow-hidden">
                <Hero />
                <div className="space-y-60 md:space-y-70">
                    <About />
                    <Experience />
                    <Projects />
                    <Contact />
                </div>
                <RightSidebar />
                <LeftSidebar />
            </main>
            <Footer />
        </>
    );
}
